### PR TITLE
New method to handle adding a new progress state + progress states for `success` and `error`

### PR DESCRIPTION
**Pull request by mbad0la**
This is in reference to #40 

Notify for review : @inator @gr2m

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Looks good to me 👍 I’ll let @inator merge it in after his review. Please rephrase the commit to something like "feat: `.success()` & `.error()` update `.progress` array"

**Comment by mbad0la** [comment]
@inator if you're fine with the PR, I'll let you know when I've rephrased the commit message, as requested by @gr2m

**Comment by gr2m** [comment]
We can use GitHub’s built-in "Squash and merge" feature for that, no need to do that manually any longer :) 
squash-and-commit

**Comment by mbad0la** [comment]
I completely forgot about that! +1 on the GIF though :p

**Comment by inator** [comment]
@gr2m & @mbad0la -
I'm not 100% on this, but would it be better to add a callback to `.addToProgressLifeCycle()` for the subsequent `return taskStore.remove(taskDoc)`?

    addToProgressLifeCycle(taskDoc, {name: 'error', error: error}, function(taskDoc){
      return taskStore.remove(taskDoc)
    })

**Comment by gr2m** [comment]
no need to, `addToProgressLifeCycle` mutates the `taskDoc` you pass in

```js
function addProgress(doc) {
  doc.progress.push({some: 'progress'})
}
doc = {foo: 'bar', progress: []}
addProgress(doc)
console.log(doc)
// logs {"foo": "bar","progress": [{"some": "progress"}]}
```

makes sense?

**Pull request merged**
